---
config:
  layout: elk
  elk:
    mergeEdges: true
    nodePlacementStrategy: NETWORK_SIMPLEX
    cycleBreakingStrategy: GREEDY
  c4:
    diagramMarginX: 25
    diagramMarginY: 25
---
C4Context
    title Open Banking com Strangler Fig [Azure]

    Person(Cliente, "Cliente", "Titular dos dados financeiros")
    Person(TPP_Developer, "TPP Developer", "Desenvolvedor de aplicacao terceira")

    System(main_system, "Open Banking Platform", "Migra incrementalmente de sistema legado para novo no contexto de open finance brasil", $sprite="img:https://icon.icepanel.io/Azure/svg/Compute/App-Services.svg")

    System_Ext(Open_Finance_Directory, "Open Finance Directory", "Diretorio de participantes")
    System_Ext(Instituicao_Receptora, "Instituicao Receptora", "ITP que recebe dados")
    System_Ext(BACEN, "BACEN", "Regulador Open Finance")

    Rel(Cliente, main_system, "Usa", "HTTPS")
    Rel(TPP_Developer, main_system, "Gerencia", "HTTPS")
    Rel(main_system, Open_Finance_Directory, "Integra com", "HTTPS/mTLS")
    Rel(main_system, Instituicao_Receptora, "Reporta para", "HTTPS")
    Rel(main_system, BACEN, "Comunica com", "HTTPS")

    UpdateElementStyle(main_system, $fontColor="#FFFFFF", $bgColor="#0078D4", $borderColor="#002050")
    UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")