---
config:
  layout: elk
  elk:
    mergeEdges: true
    nodePlacementStrategy: NETWORK_SIMPLEX
    cycleBreakingStrategy: GREEDY
  c4:
    diagramMarginX: 25
    diagramMarginY: 25
---
C4Context
    title Migracao do Legado MED via Strangler Fig [Oracle Cloud]

    Person(Vitima, "Vitima", "Correntista vitima de fraude ou falha operacional")
    Person(Analista_Fraude, "Analista Fraude", "Analisa casos MED e determina bloqueio")

    System(main_system, "PIX MED Platform", "Transicao gradual de sistema batch de devolucao para real-time MED", $sprite="img:https://icon.icepanel.io/OCI/svg/Developer-Services/Container-Engine-for-Kubernetes.svg")

    System_Ext(BACEN_MED, "BACEN MED", "API MED do Banco Central para devolucoes especiais")
    System_Ext(PSP_Recebedor, "PSP Recebedor", "PSP que recebeu o PIX objeto de devolucao")
    System_Ext(Anti_Fraud_System, "Anti-Fraud System", "Sistema de deteccao de fraude")

    Rel(Vitima, main_system, "Usa", "HTTPS")
    Rel(Analista_Fraude, main_system, "Gerencia", "HTTPS")
    Rel(main_system, BACEN_MED, "Integra com", "HTTPS/mTLS")
    Rel(main_system, PSP_Recebedor, "Reporta para", "HTTPS")
    Rel(main_system, Anti_Fraud_System, "Comunica com", "HTTPS")

    UpdateElementStyle(main_system, $fontColor="#FFFFFF", $bgColor="#F80000", $borderColor="#C74634")
    UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")