---
config:
  layout: elk
  elk:
    mergeEdges: true
    nodePlacementStrategy: NETWORK_SIMPLEX
    cycleBreakingStrategy: GREEDY
  c4:
    diagramMarginX: 25
    diagramMarginY: 25
---
C4Context
    title STR com Publish-Subscribe [AWS]

    Person(Operador_Tesouraria, "Operador Tesouraria", "Opera mesa de tesouraria")
    Person(Gerente_Liquidez, "Gerente Liquidez", "Gerencia posicao de liquidez")

    System(main_system, "STR Platform", "Broadcast de mensagens para multiplos assinantes aplicado ao contexto de sistema de transferencia de reservas", $sprite="img:https://icon.icepanel.io/AWS/svg/Containers/Elastic-Container-Service.svg")

    System_Ext(BACEN_STR, "BACEN STR", "Sistema de Transferencia de Reservas")
    System_Ext(Banco_Participante, "Banco Participante", "Banco com conta reserva")
    System_Ext(Camara_LBTR, "Camara LBTR", "Liquidacao bruta em tempo real")

    Rel(Operador_Tesouraria, main_system, "Usa", "HTTPS")
    Rel(Gerente_Liquidez, main_system, "Gerencia", "HTTPS")
    Rel(main_system, BACEN_STR, "Integra com", "HTTPS/mTLS")
    Rel(main_system, Banco_Participante, "Reporta para", "HTTPS")
    Rel(main_system, Camara_LBTR, "Comunica com", "HTTPS")

    UpdateElementStyle(main_system, $fontColor="#232F3E", $bgColor="#FF9900", $borderColor="#232F3E")
    UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")