---
config:
  layout: elk
  elk:
    mergeEdges: true
    nodePlacementStrategy: NETWORK_SIMPLEX
    cycleBreakingStrategy: GREEDY
  c4:
    diagramMarginX: 25
    diagramMarginY: 25
---
C4Context
    title Data Pipeline com Saga Choreography [Azure]

    Person(Data_Engineer, "Data Engineer", "Engenheiro de dados")
    Person(Data_Analyst, "Data Analyst", "Analista de dados")

    System(main_system, "Data Pipeline Platform", "Coordena transacoes distribuidas via coreografia de eventos no contexto de pipeline de dados e data lake", $sprite="img:https://icon.icepanel.io/Azure/svg/Compute/App-Services.svg")

    System_Ext(Core_Banking_Source, "Core Banking Source", "Fonte de dados transacionais")
    System_Ext(Payment_Source, "Payment Source", "Fonte de dados de pagamentos")
    System_Ext(BI_Tools, "BI Tools", "Ferramentas de Business Intelligence")

    Rel(Data_Engineer, main_system, "Usa", "HTTPS")
    Rel(Data_Analyst, main_system, "Gerencia", "HTTPS")
    Rel(main_system, Core_Banking_Source, "Integra com", "HTTPS/mTLS")
    Rel(main_system, Payment_Source, "Reporta para", "HTTPS")
    Rel(main_system, BI_Tools, "Comunica com", "HTTPS")

    UpdateElementStyle(main_system, $fontColor="#FFFFFF", $bgColor="#0078D4", $borderColor="#002050")
    UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")