---
config:
  layout: elk
  elk:
    mergeEdges: true
    nodePlacementStrategy: NETWORK_SIMPLEX
    cycleBreakingStrategy: GREEDY
  c4:
    diagramMarginX: 25
    diagramMarginY: 25
---
C4Context
    title Observability com Publish-Subscribe [AWS]

    Person(SRE_Engineer, "SRE Engineer", "Engenheiro de confiabilidade")
    Person(Developer, "Developer", "Desenvolvedor que monitora servicos")

    System(main_system, "Observability Platform", "Broadcast de mensagens para multiplos assinantes aplicado ao contexto de observabilidade e monitoramento", $sprite="img:https://icon.icepanel.io/AWS/svg/Containers/Elastic-Container-Service.svg")

    System_Ext(Application_Services, "Application Services", "Servicos monitorados")
    System_Ext(PagerDuty, "PagerDuty", "Plataforma de alertas")
    System_Ext(Grafana_Cloud, "Grafana Cloud", "Plataforma de dashboards")

    Rel(SRE_Engineer, main_system, "Usa", "HTTPS")
    Rel(Developer, main_system, "Gerencia", "HTTPS")
    Rel(main_system, Application_Services, "Integra com", "HTTPS/mTLS")
    Rel(main_system, PagerDuty, "Reporta para", "HTTPS")
    Rel(main_system, Grafana_Cloud, "Comunica com", "HTTPS")

    UpdateElementStyle(main_system, $fontColor="#232F3E", $bgColor="#FF9900", $borderColor="#232F3E")
    UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")