---
config:
  layout: elk
  elk:
    mergeEdges: true
    nodePlacementStrategy: NETWORK_SIMPLEX
    cycleBreakingStrategy: GREEDY
  c4:
    diagramMarginX: 25
    diagramMarginY: 25
---
C4Context
    title Payments com Strangler Fig [Azure]

    Person(Pagador, "Pagador", "Pessoa que efetua pagamento")
    Person(Recebedor, "Recebedor", "Beneficiario do pagamento")

    System(main_system, "Payments Platform", "Migra incrementalmente de sistema legado para novo no contexto de processamento de pagamentos", $sprite="img:https://icon.icepanel.io/Azure/svg/Compute/App-Services.svg")

    System_Ext(Rede_Adquirente, "Rede Adquirente", "Processadora de cartoes")
    System_Ext(PIX_SPI, "PIX SPI", "Sistema PIX do BACEN")
    System_Ext(TED_DOC_CIP, "TED DOC CIP", "Transferencias interbancarias")

    Rel(Pagador, main_system, "Usa", "HTTPS")
    Rel(Recebedor, main_system, "Gerencia", "HTTPS")
    Rel(main_system, Rede_Adquirente, "Integra com", "HTTPS/mTLS")
    Rel(main_system, PIX_SPI, "Reporta para", "HTTPS")
    Rel(main_system, TED_DOC_CIP, "Comunica com", "HTTPS")

    UpdateElementStyle(main_system, $fontColor="#FFFFFF", $bgColor="#0078D4", $borderColor="#002050")
    UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")