---
config:
  layout: elk
  elk:
    mergeEdges: true
    nodePlacementStrategy: NETWORK_SIMPLEX
    cycleBreakingStrategy: GREEDY
  c4:
    diagramMarginX: 25
    diagramMarginY: 25
---
C4Context
    title Insurance com Dead Letter Channel [Azure]

    Person(Segurado, "Segurado", "Cliente segurado")
    Person(Corretor, "Corretor", "Corretor de seguros")

    System(main_system, "Insurance Platform", "Encaminha mensagens nao processaveis para canal de dead letter aplicado ao contexto de plataforma de seguros", $sprite="img:https://icon.icepanel.io/Azure/svg/Compute/App-Services.svg")

    System_Ext(SUSEP, "SUSEP", "Superintendencia de Seguros Privados")
    System_Ext(Ressegurador, "Ressegurador", "Empresa de resseguro")
    System_Ext(Bureau_Sinistro, "Bureau Sinistro", "Base de dados de sinistros")

    Rel(Segurado, main_system, "Usa", "HTTPS")
    Rel(Corretor, main_system, "Gerencia", "HTTPS")
    Rel(main_system, SUSEP, "Integra com", "HTTPS/mTLS")
    Rel(main_system, Ressegurador, "Reporta para", "HTTPS")
    Rel(main_system, Bureau_Sinistro, "Comunica com", "HTTPS")

    UpdateElementStyle(main_system, $fontColor="#FFFFFF", $bgColor="#0078D4", $borderColor="#002050")
    UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")