---
config:
  layout: elk
  elk:
    mergeEdges: true
    nodePlacementStrategy: NETWORK_SIMPLEX
    cycleBreakingStrategy: GREEDY
  c4:
    diagramMarginX: 25
    diagramMarginY: 25
---
C4Context
    title Reconciliation com Strangler Fig [AWS]

    Person(Analista_Conciliacao, "Analista Conciliacao", "Analista de reconciliacao")
    Person(Auditor, "Auditor", "Auditor financeiro")

    System(main_system, "Reconciliation Platform", "Migra incrementalmente de sistema legado para novo no contexto de reconciliacao financeira", $sprite="img:https://icon.icepanel.io/AWS/svg/Containers/Elastic-Container-Service.svg")

    System_Ext(Core_Banking, "Core Banking", "Sistema core de contas")
    System_Ext(Payment_Processor, "Payment Processor", "Processador de pagamentos")
    System_Ext(External_Statement, "External Statement", "Extratos de contrapartes")

    Rel(Analista_Conciliacao, main_system, "Usa", "HTTPS")
    Rel(Auditor, main_system, "Gerencia", "HTTPS")
    Rel(main_system, Core_Banking, "Integra com", "HTTPS/mTLS")
    Rel(main_system, Payment_Processor, "Reporta para", "HTTPS")
    Rel(main_system, External_Statement, "Comunica com", "HTTPS")

    UpdateElementStyle(main_system, $fontColor="#232F3E", $bgColor="#FF9900", $borderColor="#232F3E")
    UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")