---
config:
  layout: elk
  elk:
    mergeEdges: true
    nodePlacementStrategy: NETWORK_SIMPLEX
    cycleBreakingStrategy: GREEDY
  c4:
    diagramMarginX: 25
    diagramMarginY: 25
---
C4Context
    title Credit Lending com Circuit Breaker [Azure]

    Person(Solicitante, "Solicitante", "Pessoa solicitando credito")
    Person(Analista_Credito, "Analista Credito", "Analista de risco de credito")

    System(main_system, "Credit Lending Platform", "Previne falhas em cascata com circuit breaker pattern no contexto de credito e emprestimos", $sprite="img:https://icon.icepanel.io/Azure/svg/Compute/App-Services.svg")

    System_Ext(Bureau_Credito_SCR, "Bureau Credito SCR", "Sistema de informacoes de credito BACEN")
    System_Ext(BACEN_SCR, "BACEN SCR", "Central de risco do BACEN")
    System_Ext(Seguradora, "Seguradora", "Seguro prestamista")

    Rel(Solicitante, main_system, "Usa", "HTTPS")
    Rel(Analista_Credito, main_system, "Gerencia", "HTTPS")
    Rel(main_system, Bureau_Credito_SCR, "Integra com", "HTTPS/mTLS")
    Rel(main_system, BACEN_SCR, "Reporta para", "HTTPS")
    Rel(main_system, Seguradora, "Comunica com", "HTTPS")

    UpdateElementStyle(main_system, $fontColor="#FFFFFF", $bgColor="#0078D4", $borderColor="#002050")
    UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")