---
config:
  layout: elk
  elk:
    mergeEdges: true
    nodePlacementStrategy: NETWORK_SIMPLEX
    cycleBreakingStrategy: GREEDY
  c4:
    diagramMarginX: 25
    diagramMarginY: 25
---
C4Context
    title Treasury com Saga Orchestration [Azure]

    Person(Tesoureiro, "Tesoureiro", "Tesoureiro da instituicao")
    Person(Operador_Mesa, "Operador Mesa", "Operador de mesa de cambio")

    System(main_system, "Treasury Platform", "Coordena transacoes distribuidas via orquestrador central no contexto de gestao de tesouraria", $sprite="img:https://icon.icepanel.io/Azure/svg/Compute/App-Services.svg")

    System_Ext(BACEN_STR, "BACEN STR", "Sistema de Transferencia de Reservas")
    System_Ext(Bloomberg_Terminal, "Bloomberg Terminal", "Terminal de dados de mercado")
    System_Ext(CETIP, "CETIP", "Central de custodia de titulos")

    Rel(Tesoureiro, main_system, "Usa", "HTTPS")
    Rel(Operador_Mesa, main_system, "Gerencia", "HTTPS")
    Rel(main_system, BACEN_STR, "Integra com", "HTTPS/mTLS")
    Rel(main_system, Bloomberg_Terminal, "Reporta para", "HTTPS")
    Rel(main_system, CETIP, "Comunica com", "HTTPS")

    UpdateElementStyle(main_system, $fontColor="#FFFFFF", $bgColor="#0078D4", $borderColor="#002050")
    UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")