---
config:
  layout: elk
  elk:
    mergeEdges: true
    nodePlacementStrategy: NETWORK_SIMPLEX
    cycleBreakingStrategy: GREEDY
  c4:
    diagramMarginX: 25
    diagramMarginY: 25
---
C4Context
    title Security IAM com Strangler Fig [AWS]

    Person(End_User, "End User", "Usuario final da plataforma")
    Person(Security_Admin, "Security Admin", "Administrador de seguranca")

    System(main_system, "Security IAM Platform", "Migra incrementalmente de sistema legado para novo no contexto de seguranca e gestao de identidade", $sprite="img:https://icon.icepanel.io/AWS/svg/Containers/Elastic-Container-Service.svg")

    System_Ext(External_IdP, "External IdP", "Provedor de identidade externo")
    System_Ext(HSM_Provider, "HSM Provider", "Hardware Security Module")
    System_Ext(SIEM, "SIEM", "Security Information and Event Management")

    Rel(End_User, main_system, "Usa", "HTTPS")
    Rel(Security_Admin, main_system, "Gerencia", "HTTPS")
    Rel(main_system, External_IdP, "Integra com", "HTTPS/mTLS")
    Rel(main_system, HSM_Provider, "Reporta para", "HTTPS")
    Rel(main_system, SIEM, "Comunica com", "HTTPS")

    UpdateElementStyle(main_system, $fontColor="#232F3E", $bgColor="#FF9900", $borderColor="#232F3E")
    UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")