---
config:
  layout: elk
  elk:
    mergeEdges: true
    nodePlacementStrategy: NETWORK_SIMPLEX
    cycleBreakingStrategy: GREEDY
  c4:
    diagramMarginX: 25
    diagramMarginY: 25
---
C4Context
    title Investments com Dead Letter Channel [Oracle Cloud]

    Person(Investidor, "Investidor", "Cliente investidor")
    Person(Assessor, "Assessor", "Assessor de investimentos")

    System(main_system, "Investments Platform", "Encaminha mensagens nao processaveis para canal de dead letter aplicado ao contexto de investimentos e patrimonio", $sprite="img:https://icon.icepanel.io/OCI/svg/Developer-Services/Container-Engine-for-Kubernetes.svg")

    System_Ext(B3_Bolsa, "B3 Bolsa", "Bolsa de Valores do Brasil")
    System_Ext(CVM, "CVM", "Comissao de Valores Mobiliarios")
    System_Ext(Custodiante, "Custodiante", "Custodia de ativos")

    Rel(Investidor, main_system, "Usa", "HTTPS")
    Rel(Assessor, main_system, "Gerencia", "HTTPS")
    Rel(main_system, B3_Bolsa, "Integra com", "HTTPS/mTLS")
    Rel(main_system, CVM, "Reporta para", "HTTPS")
    Rel(main_system, Custodiante, "Comunica com", "HTTPS")

    UpdateElementStyle(main_system, $fontColor="#FFFFFF", $bgColor="#F80000", $borderColor="#C74634")
    UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")