---
config:
  layout: elk
  elk:
    mergeEdges: true
    nodePlacementStrategy: NETWORK_SIMPLEX
    cycleBreakingStrategy: GREEDY
  c4:
    diagramMarginX: 25
    diagramMarginY: 25
---
C4Context
    title Core Banking com Saga Choreography [AWS]

    Person(Correntista, "Correntista", "Cliente com conta corrente")
    Person(Gerente_Conta, "Gerente Conta", "Gerente de relacionamento")

    System(main_system, "Core Banking Platform", "Coordena transacoes distribuidas via coreografia de eventos no contexto de plataforma core banking", $sprite="img:https://icon.icepanel.io/AWS/svg/Containers/Elastic-Container-Service.svg")

    System_Ext(CIP, "CIP", "Camara Interbancaria de Pagamentos")
    System_Ext(BACEN, "BACEN", "Banco Central do Brasil")
    System_Ext(Bureau_Credito, "Bureau Credito", "Serasa, SPC, Boa Vista")

    Rel(Correntista, main_system, "Usa", "HTTPS")
    Rel(Gerente_Conta, main_system, "Gerencia", "HTTPS")
    Rel(main_system, CIP, "Integra com", "HTTPS/mTLS")
    Rel(main_system, BACEN, "Reporta para", "HTTPS")
    Rel(main_system, Bureau_Credito, "Comunica com", "HTTPS")

    UpdateElementStyle(main_system, $fontColor="#232F3E", $bgColor="#FF9900", $borderColor="#232F3E")
    UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")