---
config:
  layout: elk
  elk:
    mergeEdges: true
    nodePlacementStrategy: NETWORK_SIMPLEX
    cycleBreakingStrategy: GREEDY
  c4:
    diagramMarginX: 25
    diagramMarginY: 25
---
C4Context
    title Anti-Fraud com Saga Orchestration [AWS]

    Person(Analista_Fraude, "Analista Fraude", "Investiga alertas de fraude")
    Person(Data_Scientist, "Data Scientist", "Treina modelos de deteccao")

    System(main_system, "Anti-Fraud Platform", "Coordena transacoes distribuidas via orquestrador central no contexto de motor anti-fraude e risco", $sprite="img:https://icon.icepanel.io/AWS/svg/Containers/Elastic-Container-Service.svg")

    System_Ext(Bureau_de_Fraude, "Bureau de Fraude", "Base de dados de fraudadores")
    System_Ext(Device_Fingerprint, "Device Fingerprint", "Servico de device ID")
    System_Ext(BACEN_MED, "BACEN MED", "Mecanismo Especial de Devolucao")

    Rel(Analista_Fraude, main_system, "Usa", "HTTPS")
    Rel(Data_Scientist, main_system, "Gerencia", "HTTPS")
    Rel(main_system, Bureau_de_Fraude, "Integra com", "HTTPS/mTLS")
    Rel(main_system, Device_Fingerprint, "Reporta para", "HTTPS")
    Rel(main_system, BACEN_MED, "Comunica com", "HTTPS")

    UpdateElementStyle(main_system, $fontColor="#232F3E", $bgColor="#FF9900", $borderColor="#232F3E")
    UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")