---
config:
  layout: elk
  elk:
    mergeEdges: true
    nodePlacementStrategy: NETWORK_SIMPLEX
    cycleBreakingStrategy: GREEDY
  c4:
    diagramMarginX: 25
    diagramMarginY: 25
---
C4Context
    title Cards com Dead Letter Channel [Azure]

    Person(Portador, "Portador", "Titular do cartao")
    Person(Operador_Cartoes, "Operador Cartoes", "Operador de gestao de cartoes")

    System(main_system, "Cards Platform", "Encaminha mensagens nao processaveis para canal de dead letter aplicado ao contexto de processamento de cartoes", $sprite="img:https://icon.icepanel.io/Azure/svg/Compute/App-Services.svg")

    System_Ext(Bandeira_Visa_Master, "Bandeira Visa Master", "Redes de cartao")
    System_Ext(TSP_Token_Requestor, "TSP Token Requestor", "Provedor de tokenizacao")
    System_Ext(Rede_Adquirente, "Rede Adquirente", "Processadora de transacoes")

    Rel(Portador, main_system, "Usa", "HTTPS")
    Rel(Operador_Cartoes, main_system, "Gerencia", "HTTPS")
    Rel(main_system, Bandeira_Visa_Master, "Integra com", "HTTPS/mTLS")
    Rel(main_system, TSP_Token_Requestor, "Reporta para", "HTTPS")
    Rel(main_system, Rede_Adquirente, "Comunica com", "HTTPS")

    UpdateElementStyle(main_system, $fontColor="#FFFFFF", $bgColor="#0078D4", $borderColor="#002050")
    UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")