---
config:
  layout: elk
  elk:
    mergeEdges: true
    nodePlacementStrategy: NETWORK_SIMPLEX
    cycleBreakingStrategy: GREEDY
  c4:
    diagramMarginX: 25
    diagramMarginY: 25
---
C4Context
    title KYC AML com Saga Choreography [Oracle Cloud]

    Person(Cliente, "Cliente", "Pessoa em processo de onboarding")
    Person(Analista_Compliance, "Analista Compliance", "Analista de PLD/FT")

    System(main_system, "KYC AML Platform", "Coordena transacoes distribuidas via coreografia de eventos no contexto de know your customer e anti-lavagem", $sprite="img:https://icon.icepanel.io/OCI/svg/Developer-Services/Container-Engine-for-Kubernetes.svg")

    System_Ext(Receita_Federal, "Receita Federal", "Validacao de CPF/CNPJ")
    System_Ext(COAF, "COAF", "Conselho de Controle de Atividades Financeiras")
    System_Ext(OFAC_Sanctions, "OFAC Sanctions", "Lista de sancoes internacionais")

    Rel(Cliente, main_system, "Usa", "HTTPS")
    Rel(Analista_Compliance, main_system, "Gerencia", "HTTPS")
    Rel(main_system, Receita_Federal, "Integra com", "HTTPS/mTLS")
    Rel(main_system, COAF, "Reporta para", "HTTPS")
    Rel(main_system, OFAC_Sanctions, "Comunica com", "HTTPS")

    UpdateElementStyle(main_system, $fontColor="#FFFFFF", $bgColor="#F80000", $borderColor="#C74634")
    UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")