---
config:
  layout: elk
  elk:
    mergeEdges: true
    nodePlacementStrategy: NETWORK_SIMPLEX
    cycleBreakingStrategy: GREEDY
  c4:
    diagramMarginX: 25
    diagramMarginY: 25
---
C4Context
    title Notification com Circuit Breaker [AWS]

    Person(End_User, "End User", "Usuario que recebe notificacoes")
    Person(Marketing_Manager, "Marketing Manager", "Gestor de campanhas")

    System(main_system, "Notification Platform", "Previne falhas em cascata com circuit breaker pattern no contexto de servicos de notificacao", $sprite="img:https://icon.icepanel.io/AWS/svg/Containers/Elastic-Container-Service.svg")

    System_Ext(Email_Provider_SES, "Email Provider SES", "Servico de email")
    System_Ext(SMS_Provider, "SMS Provider", "Provedor de SMS")
    System_Ext(Push_FCM, "Push FCM", "Firebase Cloud Messaging")

    Rel(End_User, main_system, "Usa", "HTTPS")
    Rel(Marketing_Manager, main_system, "Gerencia", "HTTPS")
    Rel(main_system, Email_Provider_SES, "Integra com", "HTTPS/mTLS")
    Rel(main_system, SMS_Provider, "Reporta para", "HTTPS")
    Rel(main_system, Push_FCM, "Comunica com", "HTTPS")

    UpdateElementStyle(main_system, $fontColor="#232F3E", $bgColor="#FF9900", $borderColor="#232F3E")
    UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")