---
config:
  layout: elk
  elk:
    mergeEdges: true
    nodePlacementStrategy: NETWORK_SIMPLEX
    cycleBreakingStrategy: GREEDY
  c4:
    diagramMarginX: 25
    diagramMarginY: 25
---
C4Context
    title Registro de Chave PIX via Content-Based Router [Oracle Cloud]

    Person(Correntista, "Correntista", "Cliente que registra e gerencia chaves PIX")
    Person(Operador_Backoffice, "Operador Backoffice", "Operador que gerencia disputas de chaves")

    System(main_system, "PIX DICT Platform", "Roteamento de registros EVP, CPF, CNPJ, email e telefone para processadores especializados", $sprite="img:https://icon.icepanel.io/OCI/svg/Developer-Services/Container-Engine-for-Kubernetes.svg")

    System_Ext(BACEN_DICT, "BACEN DICT", "API DICT do Banco Central para registro de chaves")
    System_Ext(Participante_PSP, "Participante PSP", "Instituicao participante do arranjo PIX")
    System_Ext(SPI, "SPI", "Sistema de Pagamentos Instantaneos")

    Rel(Correntista, main_system, "Usa", "HTTPS")
    Rel(Operador_Backoffice, main_system, "Gerencia", "HTTPS")
    Rel(main_system, BACEN_DICT, "Integra com", "HTTPS/mTLS")
    Rel(main_system, Participante_PSP, "Reporta para", "HTTPS")
    Rel(main_system, SPI, "Comunica com", "HTTPS")

    UpdateElementStyle(main_system, $fontColor="#FFFFFF", $bgColor="#F80000", $borderColor="#C74634")
    UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")