---
config:
  layout: elk
  elk:
    mergeEdges: true
    nodePlacementStrategy: NETWORK_SIMPLEX
    cycleBreakingStrategy: GREEDY
  c4:
    diagramMarginX: 25
    diagramMarginY: 25
---
C4Context
    title DDA com Publish-Subscribe [Oracle Cloud]

    Person(Sacado, "Sacado", "Pagador do boleto")
    Person(Cedente, "Cedente", "Emitente do boleto")

    System(main_system, "DDA Platform", "Broadcast de mensagens para multiplos assinantes aplicado ao contexto de debito direto autorizado", $sprite="img:https://icon.icepanel.io/OCI/svg/Developer-Services/Container-Engine-for-Kubernetes.svg")

    System_Ext(CIP_DDA, "CIP DDA", "Central de registro DDA")
    System_Ext(Banco_Sacado, "Banco Sacado", "Banco do pagador")
    System_Ext(Registro_Boletos, "Registro Boletos", "Sistema de registro de boletos")

    Rel(Sacado, main_system, "Usa", "HTTPS")
    Rel(Cedente, main_system, "Gerencia", "HTTPS")
    Rel(main_system, CIP_DDA, "Integra com", "HTTPS/mTLS")
    Rel(main_system, Banco_Sacado, "Reporta para", "HTTPS")
    Rel(main_system, Registro_Boletos, "Comunica com", "HTTPS")

    UpdateElementStyle(main_system, $fontColor="#FFFFFF", $bgColor="#F80000", $borderColor="#C74634")
    UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")