---
config:
  layout: elk
  elk:
    mergeEdges: true
    nodePlacementStrategy: NETWORK_SIMPLEX
    cycleBreakingStrategy: GREEDY
  c4:
    diagramMarginX: 25
    diagramMarginY: 25
---
C4Context
    title Investments com Saga Choreography [GCP]

    Person(Investidor, "Investidor", "Cliente investidor")
    Person(Assessor, "Assessor", "Assessor de investimentos")

    System(main_system, "Investments Platform", "Coordena transacoes distribuidas via coreografia de eventos no contexto de investimentos e patrimonio", $sprite="img:https://icon.icepanel.io/GCP/svg/Compute/Cloud-Run.svg")

    System_Ext(B3_Bolsa, "B3 Bolsa", "Bolsa de Valores do Brasil")
    System_Ext(CVM, "CVM", "Comissao de Valores Mobiliarios")
    System_Ext(Custodiante, "Custodiante", "Custodia de ativos")

    Rel(Investidor, main_system, "Usa", "HTTPS")
    Rel(Assessor, main_system, "Gerencia", "HTTPS")
    Rel(main_system, B3_Bolsa, "Integra com", "HTTPS/mTLS")
    Rel(main_system, CVM, "Reporta para", "HTTPS")
    Rel(main_system, Custodiante, "Comunica com", "HTTPS")

    UpdateElementStyle(main_system, $fontColor="#FFFFFF", $bgColor="#4285F4", $borderColor="#1A73E8")
    UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")