---
config:
  layout: elk
  elk:
    mergeEdges: true
    nodePlacementStrategy: NETWORK_SIMPLEX
    cycleBreakingStrategy: GREEDY
  c4:
    diagramMarginX: 25
    diagramMarginY: 25
---
C4Context
    title RSFN Connect com Saga Choreography [GCP]

    Person(Operador_RSFN, "Operador RSFN", "Opera gateway RSFN")
    Person(Admin_Certificados, "Admin Certificados", "Gerencia certificados ICP-Brasil")

    System(main_system, "RSFN Connect Platform", "Coordena transacoes distribuidas via coreografia de eventos no contexto de rede do sistema financeiro nacional", $sprite="img:https://icon.icepanel.io/GCP/svg/Compute/Cloud-Run.svg")

    System_Ext(BACEN_RSFN, "BACEN RSFN", "Rede do SFN do Banco Central")
    System_Ext(Camara_de_Compensacao, "Camara de Compensacao", "Camara de liquidacao")
    System_Ext(Participante_SFN, "Participante SFN", "Instituicao participante do SFN")

    Rel(Operador_RSFN, main_system, "Usa", "HTTPS")
    Rel(Admin_Certificados, main_system, "Gerencia", "HTTPS")
    Rel(main_system, BACEN_RSFN, "Integra com", "HTTPS/mTLS")
    Rel(main_system, Camara_de_Compensacao, "Reporta para", "HTTPS")
    Rel(main_system, Participante_SFN, "Comunica com", "HTTPS")

    UpdateElementStyle(main_system, $fontColor="#FFFFFF", $bgColor="#4285F4", $borderColor="#1A73E8")
    UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")