---
config:
  layout: elk
  elk:
    mergeEdges: true
    nodePlacementStrategy: NETWORK_SIMPLEX
    cycleBreakingStrategy: GREEDY
  c4:
    diagramMarginX: 25
    diagramMarginY: 25
---
C4Context
    title Migracao para Novo Motor PIX via Strangler Fig [AWS]

    Person(Pagador, "Pagador", "Correntista que inicia transferencia PIX")
    Person(Recebedor, "Recebedor", "Beneficiario do pagamento PIX")

    System(main_system, "PIX SPI Platform", "Migracao gradual de motor de pagamentos monolitico para microservicos", $sprite="img:https://icon.icepanel.io/AWS/svg/Containers/Elastic-Container-Service.svg")

    System_Ext(BACEN_SPI, "BACEN SPI", "Sistema de Pagamentos Instantaneos do Banco Central")
    System_Ext(Participante_Direto, "Participante Direto", "Instituicao com conta PI no BACEN")
    System_Ext(STR, "STR", "Sistema de Transferencia de Reservas")

    Rel(Pagador, main_system, "Usa", "HTTPS")
    Rel(Recebedor, main_system, "Gerencia", "HTTPS")
    Rel(main_system, BACEN_SPI, "Integra com", "HTTPS/mTLS")
    Rel(main_system, Participante_Direto, "Reporta para", "HTTPS")
    Rel(main_system, STR, "Comunica com", "HTTPS")

    UpdateElementStyle(main_system, $fontColor="#232F3E", $bgColor="#FF9900", $borderColor="#232F3E")
    UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")