---
config:
  layout: elk
  elk:
    mergeEdges: true
    nodePlacementStrategy: NETWORK_SIMPLEX
    cycleBreakingStrategy: GREEDY
  c4:
    diagramMarginX: 25
    diagramMarginY: 25
---
C4Context
    title DevOps CICD com Dead Letter Channel [Azure]

    Person(Developer, "Developer", "Desenvolvedor de software")
    Person(DevOps_Engineer, "DevOps Engineer", "Engenheiro DevOps")

    System(main_system, "DevOps CICD Platform", "Encaminha mensagens nao processaveis para canal de dead letter aplicado ao contexto de devops e pipelines ci/cd", $sprite="img:https://icon.icepanel.io/Azure/svg/Compute/App-Services.svg")

    System_Ext(Git_Repository, "Git Repository", "Repositorio de codigo fonte")
    System_Ext(Container_Registry, "Container Registry", "Registro de imagens Docker")
    System_Ext(Security_Scanner, "Security Scanner", "Scanner SAST/DAST")

    Rel(Developer, main_system, "Usa", "HTTPS")
    Rel(DevOps_Engineer, main_system, "Gerencia", "HTTPS")
    Rel(main_system, Git_Repository, "Integra com", "HTTPS/mTLS")
    Rel(main_system, Container_Registry, "Reporta para", "HTTPS")
    Rel(main_system, Security_Scanner, "Comunica com", "HTTPS")

    UpdateElementStyle(main_system, $fontColor="#FFFFFF", $bgColor="#0078D4", $borderColor="#002050")
    UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")