---
config:
  layout: elk
  elk:
    mergeEdges: true
    nodePlacementStrategy: NETWORK_SIMPLEX
    cycleBreakingStrategy: GREEDY
  c4:
    diagramMarginX: 25
    diagramMarginY: 25
---
C4Context
    title Event Driven com Wire Tap [GCP]

    Person(Developer, "Developer", "Desenvolvedor de microservicos")
    Person(Architect, "Architect", "Arquiteto de solucoes")

    System(main_system, "Event Driven Platform", "Intercepta e registra mensagens em transito para auditoria aplicado ao contexto de arquitetura event-driven", $sprite="img:https://icon.icepanel.io/GCP/svg/Compute/Cloud-Run.svg")

    System_Ext(Producer_Services, "Producer Services", "Servicos produtores de eventos")
    System_Ext(Consumer_Services, "Consumer Services", "Servicos consumidores")
    System_Ext(Monitoring, "Monitoring", "Monitoramento de eventos")

    Rel(Developer, main_system, "Usa", "HTTPS")
    Rel(Architect, main_system, "Gerencia", "HTTPS")
    Rel(main_system, Producer_Services, "Integra com", "HTTPS/mTLS")
    Rel(main_system, Consumer_Services, "Reporta para", "HTTPS")
    Rel(main_system, Monitoring, "Comunica com", "HTTPS")

    UpdateElementStyle(main_system, $fontColor="#FFFFFF", $bgColor="#4285F4", $borderColor="#1A73E8")
    UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")