---
config:
  layout: elk
  elk:
    mergeEdges: true
    nodePlacementStrategy: NETWORK_SIMPLEX
    cycleBreakingStrategy: GREEDY
  c4:
    diagramMarginX: 25
    diagramMarginY: 25
---
C4Context
    title API Gateway com Circuit Breaker [Oracle Cloud]

    Person(API_Consumer, "API Consumer", "Consumidor de APIs")
    Person(API_Developer, "API Developer", "Desenvolvedor de APIs")

    System(main_system, "API Gateway Platform", "Previne falhas em cascata com circuit breaker pattern no contexto de api gateway e hub de integracao", $sprite="img:https://icon.icepanel.io/OCI/svg/Developer-Services/Container-Engine-for-Kubernetes.svg")

    System_Ext(External_Partner, "External Partner", "Parceiro externo consumidor")
    System_Ext(Internal_Microservice, "Internal Microservice", "Microservico interno")
    System_Ext(Identity_Provider, "Identity Provider", "Provedor de identidade")

    Rel(API_Consumer, main_system, "Usa", "HTTPS")
    Rel(API_Developer, main_system, "Gerencia", "HTTPS")
    Rel(main_system, External_Partner, "Integra com", "HTTPS/mTLS")
    Rel(main_system, Internal_Microservice, "Reporta para", "HTTPS")
    Rel(main_system, Identity_Provider, "Comunica com", "HTTPS")

    UpdateElementStyle(main_system, $fontColor="#FFFFFF", $bgColor="#F80000", $borderColor="#C74634")
    UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")