---
config:
  layout: elk
  elk:
    mergeEdges: true
    nodePlacementStrategy: NETWORK_SIMPLEX
    cycleBreakingStrategy: GREEDY
  c4:
    diagramMarginX: 25
    diagramMarginY: 25
---
C4Context
    title Insurance com CQRS + Event Sourcing [Oracle Cloud]

    Person(Segurado, "Segurado", "Cliente segurado")
    Person(Corretor, "Corretor", "Corretor de seguros")

    System(main_system, "Insurance Platform", "Separa modelos de leitura e escrita com estado baseado em eventos no contexto de plataforma de seguros", $sprite="img:https://icon.icepanel.io/OCI/svg/Developer-Services/Container-Engine-for-Kubernetes.svg")

    System_Ext(SUSEP, "SUSEP", "Superintendencia de Seguros Privados")
    System_Ext(Ressegurador, "Ressegurador", "Empresa de resseguro")
    System_Ext(Bureau_Sinistro, "Bureau Sinistro", "Base de dados de sinistros")

    Rel(Segurado, main_system, "Usa", "HTTPS")
    Rel(Corretor, main_system, "Gerencia", "HTTPS")
    Rel(main_system, SUSEP, "Integra com", "HTTPS/mTLS")
    Rel(main_system, Ressegurador, "Reporta para", "HTTPS")
    Rel(main_system, Bureau_Sinistro, "Comunica com", "HTTPS")

    UpdateElementStyle(main_system, $fontColor="#FFFFFF", $bgColor="#F80000", $borderColor="#C74634")
    UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")