---
config:
  layout: elk
  elk:
    mergeEdges: true
    nodePlacementStrategy: NETWORK_SIMPLEX
    cycleBreakingStrategy: GREEDY
  c4:
    diagramMarginX: 25
    diagramMarginY: 25
---
C4Context
    title TEF com Strangler Fig [Oracle Cloud]

    Person(Lojista, "Lojista", "Estabelecimento comercial com POS")
    Person(Portador_Cartao, "Portador Cartao", "Cliente que paga com cartao")

    System(main_system, "TEF Platform", "Migra incrementalmente de sistema legado para novo no contexto de transferencia eletronica de fundos", $sprite="img:https://icon.icepanel.io/OCI/svg/Developer-Services/Container-Engine-for-Kubernetes.svg")

    System_Ext(Rede_Adquirente, "Rede Adquirente", "Processadora de transacoes")
    System_Ext(Bandeira, "Bandeira", "Visa, Mastercard, Elo")
    System_Ext(Banco_Emissor, "Banco Emissor", "Banco emissor do cartao")

    Rel(Lojista, main_system, "Usa", "HTTPS")
    Rel(Portador_Cartao, main_system, "Gerencia", "HTTPS")
    Rel(main_system, Rede_Adquirente, "Integra com", "HTTPS/mTLS")
    Rel(main_system, Bandeira, "Reporta para", "HTTPS")
    Rel(main_system, Banco_Emissor, "Comunica com", "HTTPS")

    UpdateElementStyle(main_system, $fontColor="#FFFFFF", $bgColor="#F80000", $borderColor="#C74634")
    UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")